main:
  listen : 0.0.0.0:8080
  confurl : 127.0.0.1:4141
  healtchecks : 2
  # authtype : apikey , basic, jwt, none
  authtype: none
  configauth : yes
  accesslog: off
dnsconfig:
  enabled : no
  dnsservers:
     - 192.168.10.104:8600
     - 192.168.10.105:8600
     - 192.168.10.106:8600
  srvrecords:
     - name    : p1.netangels.net:8080
       address : nginx-consul-NginX-health.tcp.service.consul
     - name    : p2.netangels.net:8080
       address : devecho-devEcho-health.tcp.service.consul
tls:
  enabled : no
  certificate : /tmp/fullchain.cer
  privatekey : /tmp/netangels.net.key
  listen : 0.0.0.0:8443
client:
  clientauth : no
  clientuser : test
  clientpass : Te$ting
  maxidle : 100
  maxperhost : 10
  maxidleperhost : 10
  idletimeout : 90
  timeout : 10
monitoring:
  enabled : yes
  url:  127.0.0.1:9191
  #;user: admin
  #pass: $ecretPaSs