[main]
listen : 0.0.0.0:8080
healtchecks : 2

[server]
# authtype : apikey , basic, none
authtype : none
accesslog  : off

[client]
clientauth : false
clientuser : test
clientpass : Te$ting
maxidle : 100
maxperhost : 10
maxidleperhost : 10
idletimeout : 90
timeout : 10

[monitoring]
enabled : true
url:  http://127.0.0.1:9191
;user: admin
;pass: $ecretPaSs