[main]
listen : 0.0.0.0:8080
confurl : 127.0.0.1:4141
healtchecks : 2

[tls]
enbaled : bi
certificate : /tmp/fullchain.cer
privatekey : /tmp/netangels.net.key
listen : 0.0.0.0:8443

[server]
# authtype : apikey , basic, jwt, none
authtype : none
accesslog  : off

[client]
clientauth : false
clientuser : test
clientpass : Te$ting
maxidle : 100
maxperhost : 10
maxidleperhost : 10
idletimeout : 90
timeout : 10

[monitoring]
enabled : true
url:  127.0.0.1:9191
;user: admin
;pass: $ecretPaSs